### ISSUE TITLE
Phantom typer

### ISSUE THREAD

**Issue by ray-x** [liuchengxu/vim-clap#580]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
Well, the issue happened from time to time. Did not find a way to reproduce it yet. Curious to know if anyone saw this before.

**Environment (please complete the following information):**
 - OS: MacOS
 - (Neo)Vim version: 0.5 nightly
 - vim-clap version: latest
 - Have you reproduced with a minimal vimrc: no. the issue happens randomly.

**Describe the bug**

![clap](https://user-images.githubusercontent.com/1681295/98053610-05b67e00-1e8d-11eb-8782-754ffd794f64.gif)

Please refer to the image.
Seems it trying to autocomplete my typing. I did not use `tab` to auto-complete my typing. The only thing I did was typed `vi` and it autocomplete to `vimrc`, after that I trying to backspace, but the deleted characters popup again...

**Clap debug**

```
            has cargo: 1
            has maple: /Users/ray.xu/.cache/dein/repos/github.com/liuchengxu/vim-clap/bin/maple
           maple info: version 0.1.21 (git v0.21), built for x86_64-apple-darwin by rustc 1.46.0 (04488afe3 2020-08-24).

         has +python3: 1
has py dynamic module: 0
            has ctags: ctags with JSON output support
     Current FileType: startify
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/Users/ray.xu/.cache/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_background_shadow_blend = 50
    let g:clap_current_selection_sign = {'texthl': 'ClapCurrentSelectionSign', 'linehl': 'ClapCurrentSelection', 'text': ''}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_background_shadow = v:true
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '10%', 'row': '13%', 'width': '71%', 'relative': 'editor', 'height': '39%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 10
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'curve'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_selected_sign = {'texthl': 'ClapSelectedSign', 'linehl': 'ClapSelected', 'text': ''}
  Provider Variables:
                     []
```

**To Reproduce**
Steps to reproduce the behavior:  It not reproducible with minvimrc. Also is not 100% reproducible. But it is annoying when it happens. Some time restart nvim could solve this issue.

I am more curious which might trigger this behavior.

**Comment by CKolkey** [comment]
This is happening to me on linux as well. It's also quite random, and restarting nvim does seem to reset it, for at least a period of time.

**Comment by romgrk** [comment]
Questions:
 - When have you noticed the issue for the first time? 
 - Once it starts happening, does it happen consistently? 
 - Does it happen for all providers?
 - Does it happen always when there is a single entry left as in your screenshot?
 - Any other context that could help us reproduce?

**Comment by CKolkey** [comment]
- The issue first occurred yesterday. (3/11/2020)
- Once it starts, it _always_ happens.
- It is identical across providers. The same autocompletion is used.
- It occurs for me with many entries (files in app dir) or none (`:Clap bcommits` is currently empty for me, for example)
- Sadly I have not seen a pattern in invoking it.

**Comment by romgrk** [comment]
Are you using vim-plug, and if so can you run [PlugDiff](https://github.com/junegunn/vim-plug/wiki/tutorial#reviewing-the-changes) to pinpoint the last good known commit before that? Or do you know when was the last time you updated clap?

Once it starts happening, can you run `set verbosefile=clap-log.txt verbose=12`, then reproduce the issue, then `set verbose=0` and share the output? Do it as fast as possible because it will reduce the size of the log file and help us identify the issue.

Do you have any other type of configuration for clap that isn't listed here such as additional mappings run when `clap_input` filetype is set?

**Comment by ray-x** [comment]
Please refer to the gif I uploaded in original `Describe the bug`
In the short video, after I typed `vi`. It always trying to autocomplete it to vimrc. I kept backspace, but not helpful.
I did try a vimrc.min with clap and `completion.nvim` . Bug could not reproduce.

Bellow is a log when I backspace and got auto-completed.

```

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Executing CursorMovedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Executing CompleteDone Autocommands for "*"
autocommand call vsnip_integ#on_complete_done(v:completed_item)

Executing CompleteDone Autocommands for "*"
autocommand call float_preview#_complete_done()

Executing CompleteDone Autocommands for "<buffer=4>"
autocommand lua require'completion'.on_CompleteDone()

Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [No Name]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Executing CursorMovedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Executing CompleteDone Autocommands for "*"
autocommand call vsnip_integ#on_complete_done(v:completed_item)

Executing CompleteDone Autocommands for "*"
autocommand call float_preview#_complete_done()

Executing CompleteDone Autocommands for "<buffer=4>"
autocommand lua require'completion'.on_CompleteDone()

Executing CursorMovedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [No Name]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Executing CursorMovedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Executing CompleteDone Autocommands for "*"
autocommand call vsnip_integ#on_complete_done(v:completed_item)

Executing CompleteDone Autocommands for "*"
autocommand call float_preview#_complete_done()

Executing CompleteDone Autocommands for "<buffer=4>"
autocommand lua require'completion'.on_CompleteDone()

Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [No Name]
Scanning: [Scratch]
Scanning: [Scratch]
Scanning: [Scratch]
Executing CursorMovedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing CursorMovedI Autocommands for "<buffer=4>"
autocommand call clap#handler#on_typed()

Executing TextChangedI Autocommands for "*"
autocommand call s:Highlight_Matching_Pair()

Executing TextChangedI Autocommands for "*"
autocommand call s:on_text_changed()

Executing FocusLost Autocommands for "*"
autocommand silent! lua require('scrollbar').clear()

Executing FocusLost Autocommands for "*"
autocommand silent! lua require('scrollbar').clear()

Executing FocusGained Autocommands for "*"
autocommand silent! lua require('scrollbar').show()

Executing FocusGained Autocommands for "*"
autocommand silent! lua require('scrollbar').show()

Executing FocusGained Autocommands for "*"
autocommand checktime

Executing CompleteDone Autocommands for "*"
autocommand call vsnip_integ#on_complete_done(v:completed_item)

Executing CompleteDone Autocommands for "*"
autocommand call float_preview#_complete_done()
```

**Comment by CKolkey** [comment]
I update plugins very frequently, and as I said it began yesterday. The only two updates would have been #577 and #578.

**Comment by romgrk** [comment]
And could you confirm if it still happens if you `git checkout a7b26e5`, just before those PRs?

**Comment by romgrk** [comment]
Correction, after reviewing #578 we can eliminate it because it only touches `filer` related files. Could you try by reverting only #577?

```
git revert 04708737f5cd6fedee4846b18fe580d3f2ae31fc
```

**Comment by CKolkey** [comment]
I've checked out master then run `git revert 04708737f5cd6fedee4846b18fe580d3f2ae31fc` and have not encountered the issue after a few hours of use. I'll update this comment if that changes :)

**Comment by romgrk** [comment]
I see that you're both using `nvim-lua/completion.nvim`. Does the issue happens when disabling that plugin?

**Comment by ray-x** [comment]
For me. In a minimum vimrc with nvim-lua/completion.nvim and clap. The issue not reproducible. 
In my normal vim setup, if I disable completion, it will together disable around 10 plugins. The issue also gone.
Also, completion.nvim will not autocomplete when delete typed in with backspace. The issue also happened when I delete the auto-typed character.

**Comment by CKolkey** [comment]
I've also swapped out `nvim-lua/completion.nvim` for `deoplete` and have not encountered the autocomplete issue so far.

**Comment by ray-x** [comment]
swap to `nvim-lua/completion.nvim` would be lots of turmoils for me.
@romgrk Alternatively. I think I could try to disable completion when clap is active and check how it works.
What would be the identifier I could try?  e.g filetype for the clap input window?

**Comment by romgrk** [comment]
Input window has `clap_input` filetype. It's quite intriguing that the changes in #577 could introduce the behavior. After reviewing clap's code, I'd tend to think that it's indeed not clap that is doing the phantom typing because the only place in the codebase where we seem to set the input window prompt, other than clearing it, is here:
https://github.com/liuchengxu/vim-clap/blob/992c2d43318ba096eedac0592a0c2d6f90fed236/autoload/clap/api.vim#L421

This case is however only hit when the provider has a `.query` key, which isn't the case for the files provider in the screenshot.

I'll open an issue with completion.nvim to see if they'd have any insight.

**Comment by ray-x** [comment]
Some updates. 
I am turning off autocompletion  when buffer type is `clap_input` so far so good

**Comment by liuchengxu** [comment]
>https://github.com/liuchengxu/vim-clap/blob/d7bbe7529680662025f633954501a537ba226942/autoload/clap/floating_win.vim#L229

If this indeed helps, we should disable `completion-nvim` like deoplete, coc.nvim then:

https://github.com/liuchengxu/vim-clap/blob/d7bbe7529680662025f633954501a537ba226942/autoload/clap/floating_win.vim#L229-L235

**Comment by romgrk** [comment]
Feels wrong to need to disable each autocompletion framework by itself. There should be a way to tell "this buffer is mine, no-auto-complete". What about we propose a `b:autocomplete = v:false` to the completion frameworks? Could even be proposed upstream to vim/neovim. Otherwise all plugins creating their own UI will run into this kind of issue.

ping @chemzqm, @Shougo, @haorenW1025, any opinion on this?

**Comment by chemzqm** [comment]
Why not change the buftype to nofile?

**Comment by liuchengxu** [comment]
>Why not change the buftype to nofile?

By convention, using a filetype makes user able to easily customize the related mappings/options.

**Comment by Shougo** [comment]
> There should be a way to tell "this buffer is mine, no-auto-complete". 

Nothing unfortunately,
deoplete checks `buftype=nofile`.

**Comment by chemzqm** [comment]
> > Why not change the buftype to nofile?
> 
> By convention, using a filetype makes user able to easily customize the related mappings/options.

It's `buftype` option, you can still use any filetype for that buffer.

**Comment by liuchengxu** [comment]
>It's buftype option, you can still use any filetype for that buffer.

Ok, I missed that, but it's already done https://github.com/liuchengxu/vim-clap/blob/d7bbe7529680662025f633954501a537ba226942/ftplugin/clap_input.vim#L17 .

**Comment by chemzqm** [comment]
That's enough, coc.nvim does nothing with nofile buffer.

**Comment by romgrk** [comment]
> Ok, I missed that, but it's already done

So normally we should be able to remove the lines to turn off auto-completion for coc & deoplete. I've tested both frameworks just now while disabling our turn-off code. coc.nvim seems to be behaving correctly. Deoplete on the other hands seems to be triggered even though `buftype=nofile` is set:

![Screenshot from 2020-11-06 22-21-38](https://user-images.githubusercontent.com/1423607/98430850-a61fc480-207e-11eb-9b9d-00ead8e38163.png)

At which moment is deoplete checking for the buftype option? IMHO it would be possible that it's doing so right after it's opened, but the buftype option is set after deoplete's check runs.

For coc, how and when are you checking for buftype? Are you listening to `autocmd OptionSet buftype`?

**Comment by chemzqm** [comment]
> Are you listening to autocmd OptionSet buftype?

No, it's checked after buffer create, maybe you need `+set\ buftype=nofile` for buffer create command, or use `:noa` for it, so other plugins can't notice the buffer create.

**Comment by romgrk** [comment]
@liuchengxu On vim, we're using `popup_create([], opts)` which will have `buftype=popup`. On neovim, we're using `let s:input_bufnr = nvim_create_buf(v:false, v:true)`. I'd have no trouble using `noautocmd` on neovim as I don't see any reason for other plugins to touch our precious buffer; `buftype=nofile` can be set in the subsequent lines.

But anyway I'd wait for an answer from completion.nvim maintainers as the phantom typing problem might come from there, I'll update if they answer on the issue I opened on their repo.

**Comment by liuchengxu** [comment]
I'm ok with that too as long as it can really avoid these issues :).

**Comment by Shougo** [comment]
> At which moment is deoplete checking for the buftype option? IMHO it would be possible that it's doing so right after it's opened, but the buftype option is set after deoplete's check runs.

I have fixed the problem.  Please use the latest version of deoplete.

**Comment by liuchengxu** [comment]
Can you help confirm if the following patch makes this issue disappear even when the completion plugin like `completion-nvim` is enabled? @ray-x  @CKolkey 

```diff
diff --git a/autoload/clap/floating_win.vim b/autoload/clap/floating_win.vim
index cd83601..b9d3c02 100644
--- a/autoload/clap/floating_win.vim
+++ b/autoload/clap/floating_win.vim
@@ -16,7 +16,7 @@ let s:shadow_bufnr = nvim_create_buf(v:false, v:true)
 let s:spinner_bufnr = nvim_create_buf(v:false, v:true)
 let g:clap.spinner.bufnr = s:spinner_bufnr
 
-let s:input_bufnr = nvim_create_buf(v:false, v:true)
+noautocmd let s:input_bufnr = nvim_create_buf(v:false, v:true)
 let g:clap.input.bufnr = s:input_bufnr
 
 let s:display_bufnr = nvim_create_buf(v:false, v:true)
@@ -199,7 +199,7 @@ function! g:clap#floating_win#input.open() abort
   let g:clap#floating_win#input.width = opts.width
 
   if !nvim_buf_is_valid(s:input_bufnr)
-    let s:input_bufnr = nvim_create_buf(v:false, v:true)
+    noautocmd let s:input_bufnr = nvim_create_buf(v:false, v:true)
     let g:clap.input.bufnr = s:input_bufnr
   endif
   silent let s:input_winid = nvim_open_win(s:input_bufnr, v:true, opts)
```

**Comment by ray-x** [comment]
Manually updated floating_win.vim and enable completion.  From what I saw, this patch does not fix the issue.

**Comment by liuchengxu** [comment]
https://github.com/nvim-lua/completion-nvim/issues/261#issuecomment-736520073 @ray-x Does this workaround work for you? I can't think of more that can be done on the vim-clap side.

**Comment by ray-x** [comment]
Yes, the workaround works perfectly fine.  
Maybe put some notes in README.md .
I am using compe and have this in my config:
```lua
 vim.api.nvim_command("autocmd FileType clap_input call compe#setup({ 'enabled': v:false }, 0)")
```

**Comment by liuchengxu** [comment]
>Maybe put some notes in README.md .

I don't use compe, feel free to create a PR for that :(.
